[build]
  base = "frontend"      # Dossier où exécuter la commande
  publish = "itcg-frontend/dist"
  command = "npm install && npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://itcg.onrender.com/api/:splat"  # Proxy vers le backend
  status = 200